# -*- coding: utf-8 -*-
"""bike-sharing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nz-Xln6Yic6JjYyDPr--3UDu8Mzc4yKg

# A. Pertanyaan Bisnis

1. Berapa Total penyewa pada tahun 2011 dan 2012, serta total secara keseluruhan?
2. Berapa total penyewa casual dan registered pada tahun 2011 dan 2012, serta total keseluruhan?
3. Bulan apa dengan total penyewaan sepeda tertinggi dan bagaimana trend pada bulan tersebut?
4.  Musim dengan total penyewaan tertinggi?
5. Pada Saat Weekday atau Weekend mana dengan total penyewaan sepeda tertinggi?
6. Hari apa dengan penyewaan tertinggi  dan terendah?
7. Bagaimana trend penyewaan sepeda berdasarkan jam?

# B. Mengenal Data
"""

# Import Library yang dibutuhkan
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Data
data_harian = pd.read_csv("/content/drive/MyDrive/Career Development/portfolio-magang-2026/analysis-data-with-python/bike-sharing/data/day.csv")
data_perjam = pd.read_csv("/content/drive/MyDrive/Career Development/portfolio-magang-2026/analysis-data-with-python/bike-sharing/data/hour.csv")

# Melihat data harian secara garis besar
data_harian.head(5)

# Melihat data penyewaan sepeda berdasarkan jam secara garis besar
data_perjam.head(5)

"""  - instans : index
  - dteday : tanggal dilakukan penyewaan
  - season : musim dilakukan penyewaan
  - yr : Tahun dilakukan penyewaan
  - mnth : bulan dilakukan penyewaan
  - holiday : penyewaan pada hari libur
  - weekday : penyewaan dalam harian (monday, sunday, tuesday, etc)
  - working day : penyewaan pada hari kerja
  - weathersit : penyewaan pada suasana musim
  - temp : Temperature suhu dalam Celcius yang sudah dinormalisasikan
  - atemp : Suasana suhu dalam Celcius yang sudah dinormalisasikan
  - hum : kelembapan udara yang sudah dinormalisasikan
  - windspeed : kecepatan angin yang sudah dinormalisasikan
  - casual : jumlah orang yang tidak terdaftar dalam penyewaan sepeda
  - registered : jumalah orang yang terdaftar dalam penyewaan sepeda
  - cnt : total seluruh orang yang melakukan penyewaan sepeda

Pada kedua dataset, yaitu data harian dan data berbasis jam, secara umum variabel atau nama kolom yang digunakan adalah sama. Namun, pada dataset berbasis jam terdapat penambahan variabel hr yang merepresentasikan jam pengamatan (0–24). Selain itu, nilai pada masing-masing variabel di kedua dataset tersebut berbeda karena merepresentasikan kondisi dan skala waktu pengamatan yang berbeda.
"""

# Melihat tipe data pada data harian
data_harian.info()

# Melihat tipe data pada data berdasarkan jam
data_perjam.info()

"""- Pada data berdasarkan harian memiliki baris berjumlah 731 dan 16 Kolom. Data tersebut memiliki 15 tipe data numerik dan 1 kategori

- Pada data berdasarkan jam memiliki baris berjumlah 17379 dan 17 Kolom. Data tersebut memiliki 16 tipe data numerik dan 1 kategori

"""

# Melihat Missing Value pada data berdasarkan hari
data_harian.isnull().sum()

# Melihat Missing Value pada data berdasarkan jam
data_perjam.isnull().sum()

# Melihat duplikat pada data berdasarkan hari
data_harian.duplicated().sum()

# Melihat duplikat pada data berdasarkan jam
data_harian.duplicated().sum()

"""Pada kedua data berdasrkan hari dan jam tidak ada missing value dan nilai yang duplikat

# Membersihkan Data
"""

# daftar kolom yang akan dihapus
kolom_dihapus = ['instant', 'temp', 'atemp', 'hum', 'windspeed']

# Hapus kolompada data harian dan data berdasarkan jam
data_harian_clean = data_harian.drop(columns=kolom_dihapus)
data_perjam_clean = data_perjam.drop(columns=kolom_dihapus)

"""- Kolom instant dihapus karena hanya berfungsi sebagai penanda urutan (indeks) data dan tidak memiliki makna analitis atau kontribusi terhadap pola penyewaan sepeda. Informasi urutan data telah diwakili oleh struktur indeks DataFrame maupun kolom tanggal (dteday).

- Kolom temp, atemp, hum, dan windspeed dihapus karena nilainya seperti telah dinormalisasi, sehingga sulit untuk diinterpretasikan secara langsung dalam satuan aslinya (misalnya derajat Celcius atau persentase kelembapan). Selain itu, dalam analisis ini fokus diarahkan pada variabel waktu dan perilaku penyewaan, sehingga variabel lingkungan yang telah dinormalisasi tersebut tidak digunakan lebih lanjut.
"""

# mengubah tipe data pada kolom dteday menjadi datetime
datetime_columns = ["dteday"]
for column in datetime_columns:
    data_harian_clean[column] = pd.to_datetime(data_harian_clean[column])
    data_perjam_clean[column] = pd.to_datetime(data_perjam_clean[column])

# Melakukan label encoding untuk mengganti value pada beberapa variabel di data harian

season = {1: "Spring", 2: "Summer", 3: "Fall", 4: "Winter"}
yr = {0: 2011, 1: 2012}
holiday = {0: "not holiday", 1: "holiday"}
weekday = {
    0: "sunday", 1: "monday", 2: "tuesday",
    3: "wednesday", 4: "thursday", 5: "friday", 6: "saturday"
}
workingday = {0: "weekend", 1: "not weekend"}
weathersit = {
    1: "Clear, Few clouds, Partly cloudy, Partly cloudy",
    2: "Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist",
    3: "Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds",
    4: "Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog"
}
mnth = {
    1: "January", 2: "February", 3: "March", 4: "April",
    5: "May", 6: "June", 7: "July", 8: "August",
    9: "September", 10: "October", 11: "November", 12: "December"
}

data_harian_clean["season"] = data_harian_clean["season"].replace(season)
data_harian_clean["yr"] = data_harian_clean["yr"].replace(yr)
data_harian_clean["holiday"] = data_harian_clean["holiday"].replace(holiday)
data_harian_clean["weekday"] = data_harian_clean["weekday"].replace(weekday)
data_harian_clean["workingday"] = data_harian_clean["workingday"].replace(workingday)
data_harian_clean["weathersit"] = data_harian_clean["weathersit"].replace(weathersit)
data_harian_clean["mnth"] = data_harian_clean["mnth"].replace(mnth)

# Melakukan label encoding untuk mengganti value pada beberapa variabel pada data berdasarkan jam

season = {1: "Spring", 2: "Summer", 3: "Fall", 4: "Winter"}
yr = {0: 2011, 1: 2012}
holiday = {0: "not holiday", 1: "holiday"}
weekday = {
    0: "sunday", 1: "monday", 2: "tuesday",
    3: "wednesday", 4: "thursday", 5: "friday", 6: "saturday"
}
workingday = {0: "weekend", 1: "not weekend"}
weathersit = {
    1: "Clear, Few clouds, Partly cloudy, Partly cloudy",
    2: "Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist",
    3: "Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds",
    4: "Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog"
}
mnth = {
    1: "January", 2: "February", 3: "March", 4: "April",
    5: "May", 6: "June", 7: "July", 8: "August",
    9: "September", 10: "October", 11: "November", 12: "December"
}

data_perjam_clean["season"] = data_perjam_clean["season"].replace(season)
data_perjam_clean["yr"] = data_perjam_clean["yr"].replace(yr)
data_perjam_clean["holiday"] = data_perjam_clean["holiday"].replace(holiday)
data_perjam_clean["weekday"] = data_perjam_clean["weekday"].replace(weekday)
data_perjam_clean["workingday"] = data_perjam_clean["workingday"].replace(workingday)
data_perjam_clean["weathersit"] = data_perjam_clean["weathersit"].replace(weathersit)
data_perjam_clean["mnth"] = data_perjam_clean["mnth"].replace(mnth)

# buat kolom nama hari di data harian
data_harian_clean['day_name'] = data_harian_clean['dteday'].dt.day_name()
data_harian_clean[['dteday', 'day_name']].head()

"""# Eksplorasi Data"""

data_harian_clean

"""## 1. Berapa Total penyewa pada tahun 2011 dan 2012, serta total secara keseluruhan?"""

tahun_2011 = data_harian_clean[data_harian_clean['yr'] == 2011]
tahun_2012 = data_harian_clean[data_harian_clean['yr'] == 2012]
total_penyewa_2011 = tahun_2011['cnt'].sum()
total_penyewa_2012 = tahun_2012['cnt'].sum()

# total keseluruhan
total_keseluruhan = total_penyewa_2011 + total_penyewa_2012

# data
kategori = ['2011', '2012', 'Total']
total_penyewa = [total_penyewa_2011, total_penyewa_2012, total_keseluruhan]

# warna (biru muda berbeda + biru tua)
warna = ['#8ecae6', '#219ebc', '#023047']

plt.figure(figsize=(8, 5))
bars = plt.bar(kategori, total_penyewa, color=warna)

plt.xlabel('Kategori')
plt.ylabel('Total Penyewa')
plt.title('Total Penyewa Sepeda Tahun 2011, 2012, dan Keseluruhan')

# tampilkan nilai di atas bar
for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height,
        f'{int(height):,}',
        ha='center',
        va='bottom'
    )

plt.show()

"""## 2. Berapa total penyewa casual dan registered pada tahun 2011 dan 2012, serta total keseluruhan?"""

# hitung total
casual_2011 = data_harian_clean[data_harian_clean['yr'] == 2011]['casual'].sum()
registered_2011 = data_harian_clean[data_harian_clean['yr'] == 2011]['registered'].sum()

casual_2012 = data_harian_clean[data_harian_clean['yr'] == 2012]['casual'].sum()
registered_2012 = data_harian_clean[data_harian_clean['yr'] == 2012]['registered'].sum()

casual_total = casual_2011 + casual_2012
registered_total = registered_2011 + registered_2012

# data untuk plot
labels = ['2011', '2012', 'Total']
casual = [casual_2011, casual_2012, casual_total]
registered = [registered_2011, registered_2012, registered_total]

x = np.arange(len(labels))
width = 0.35

# warna
warna_casual = '#f4a7b9'      # merah muda
warna_registered = '#9ad29a'  # hijau muda

# plot
plt.figure(figsize=(9, 5))
bar1 = plt.bar(x - width/2, casual, width, label='Casual', color=warna_casual)
bar2 = plt.bar(x + width/2, registered, width, label='Registered', color=warna_registered)

plt.xlabel('Tahun')
plt.ylabel('Total Penyewa')
plt.title('Perbandingan Penyewa Casual dan Registered (2011, 2012, dan Total)')
plt.xticks(x, labels)
plt.legend()

# tampilkan nilai di atas bar
for bars in [bar1, bar2]:
    for bar in bars:
        height = bar.get_height()
        plt.text(
            bar.get_x() + bar.get_width() / 2,
            height,
            f'{int(height):,}',
            ha='center',
            va='bottom'
        )

plt.show()

"""## 3. Bulan apa dengan total penyewaan sepeda tertinggi dan bagaimana trend pada bulan tersebut?


"""

# Melihat Jumlah pengunjung berdasarkan bulan
hasil_bulan = data_harian_clean.groupby("mnth").agg({
    "cnt" : ["sum"]})

hasil_bulan.columns = ['total_cnt']

# urutkan dari terbesar ke terkecil
hasil_bulan_sorted = hasil_bulan.sort_values(by='total_cnt', ascending=False)

# buat gradasi warna merah
colors = plt.cm.Reds(
    np.linspace(0.9, 0.4, len(hasil_bulan_sorted))
)

# plot bar chart
plt.figure(figsize=(10, 5))
plt.bar(
    hasil_bulan_sorted.index,
    hasil_bulan_sorted['total_cnt'],
    color=colors
)

plt.xlabel('Bulan')
plt.ylabel('Total Penyewa')
plt.title('Jumlah Penyewa Sepeda per Bulan')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# urutan bulan
urutan_bulan = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
]

# data 2011
bulan_2011 = (
    data_harian_clean[data_harian_clean['yr'] == 2011]
    .groupby('mnth')['cnt']
    .sum()
    .reindex(urutan_bulan)
)

# data 2012
bulan_2012 = (
    data_harian_clean[data_harian_clean['yr'] == 2012]
    .groupby('mnth')['cnt']
    .sum()
    .reindex(urutan_bulan)
)

# plot line chart
plt.figure(figsize=(10, 5))
plt.plot(urutan_bulan, bulan_2011, marker='o', label='2011')
plt.plot(urutan_bulan, bulan_2012, marker='o', label='2012')

plt.xlabel('Bulan')
plt.ylabel('Total Penyewa')
plt.title('Jumlah Penyewa Sepeda per Bulan (2011 vs 2012)')
plt.legend()
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""## 4. Musim dengan total penyewaan tertinggi?"""

# agregasi
hasil_musim = data_harian.groupby("season")["cnt"].sum().reset_index()

# mapping label musim
season_map = {
    1: 'Spring',
    2: 'Summer',
    3: 'Fall',
    4: 'Winter'
}
hasil_musim['season'] = hasil_musim['season'].map(season_map)

# plot bar chart
plt.figure(figsize=(8, 5))
warna = ['#4e79a7', '#59a14f', '#f28e2b', '#af7aa1']

bars = plt.bar(
    hasil_musim['season'],
    hasil_musim['cnt'],
    color=warna
)

plt.xlabel('Musim')
plt.ylabel('Total Penyewa')
plt.title('Jumlah Penyewa Sepeda Berdasarkan Musim')

# tampilkan nilai di atas bar
for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height,
        f'{int(height):,}',
        ha='center',
        va='bottom'
    )

plt.tight_layout()
plt.show()

"""## 5. Pada saat Weekday atau Weekend mana dengan total penyewaan tertinggi?"""

# agregasi
total_workingday = data_harian_clean.groupby("workingday").agg({
    "cnt": "sum"
}).reset_index()

# warna berbeda (aman & tidak bentrok)
warna = ['#f28e2b', '#59a14f']  # oranye & hijau

plt.figure(figsize=(7, 7))

plt.pie(
    total_workingday['cnt'],
    labels=total_workingday['workingday'],
    colors=warna,
    autopct='%1.1f%%',
    startangle=90,
    wedgeprops={'edgecolor': 'white'}
)

plt.title('Proporsi Total Penyewa Sepeda\nHari Kerja vs Akhir Pekan')
plt.axis('equal')  # agar pie bulat sempurna

plt.tight_layout()
plt.show()

"""## 6. Apa hari dengan penjualan Tertinggi?"""

# Melihat Jumlah pengunjung berdasarkan hari
hasil_hari = data_perjam_clean.groupby("weekday").agg({
    "cnt" : ["sum"]}).sort_values(("cnt", "sum"), ascending=False)

hasil_hari.columns = ['total_cnt']
hasil_hari = hasil_hari.reset_index()

# palet warna (gradasi biru aman & rapi)
warna = [
    '#1f77b4', '#4e79a7', '#6baed6',
    '#9ecae1', '#c6dbef', '#deebf7', '#eff3ff'
]

plt.figure(figsize=(10, 5))

bars = plt.bar(
    hasil_hari['weekday'],
    hasil_hari['total_cnt'],
    color=warna[:len(hasil_hari)]
)

plt.xlabel('Hari')
plt.ylabel('Total Penyewa')
plt.title('Jumlah Penyewa Sepeda Berdasarkan Hari')

# tampilkan nilai di atas bar
for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height,
        f'{int(height):,}',
        ha='center',
        va='bottom'
    )

plt.tight_layout()
plt.show()

"""## 7. Jam Berapa saja yang memiliki total penyewaan tertinggi?"""

# Melihat Jumlah pengunjung berdasarkan jam
total_jam = data_perjam_clean.groupby("hr").agg({
    "cnt" : ["sum"]}).sort_values(("cnt", "sum"), ascending=False)

total_jam.columns = ['total_cnt']
total_jam = total_jam.reset_index()

# urutkan berdasarkan jam (penting untuk line chart)
total_jam = total_jam.sort_values('hr')

plt.figure(figsize=(12, 5))

plt.plot(
    total_jam['hr'],
    total_jam['total_cnt'],
    marker='o',
    linewidth=2
)

plt.xlabel('Jam')
plt.ylabel('Total Penyewa')
plt.title('Jumlah Penyewa Sepeda Berdasarkan Jam')

plt.xticks(range(0, 24))
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()